name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to push changes
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: SirAllap
          svg_out_path: assets/github-contribution-grid-snake.svg
          # For dark mode version add:
          # svg_out_path_dark: assets/github-contribution-grid-snake-dark.svg

      - name: Commit and push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add assets/
          git commit -m "Update contribution snake"
          git push
