name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
    
      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: SirAllap
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
    
      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add -A
          git commit -m "Update contribution snake"
          git push
